### ISSUE TITLE
UI Update: Change color titles to be more visible against color background

### ISSUE THREAD

**Issue by nielubowicz** [nielubowicz/ColorScheme#4]
Maybe Vibrancy will help?
Or I may just have to do color matching / flipping -- there must be a way to mathematically get the color inverse.

**Comment by nielubowicz** [comment]
Inverse Colors -- http://stackoverflow.com/a/5901586
Color brightness -- http://stackoverflow.com/questions/2509443/check-if-uicolor-is-dark-or-bright

**Comment by Nadohs** [comment]
I saw a talk about accessibility standards for web that mentioned color contrast ratios recently, which I think could apply to this
http://www.msfw.com/Services/ContrastRatioCalculator
- My plan would be to calculate color ratio between 1)  target color and black(for text) 2) target color and white(for text) - Then use which ever combination has the higher contrast ratio. 
  whichever has the higher

**Comment by nielubowicz** [comment]
That's essentially what the two SO posts are about above: the first calculates and inverse color, and the second does a quick calculation like the one you mentioned -- light or dark

**Comment by Nadohs** [comment]
ok yeah that makes sense
